"""
audit_data.py — Systematic data quality audit of the Northwind database.

Runs six independent audit passes and reports findings:
  1. Structural    - table sizes, empty tables
  2. BLOB scan     - binary columns that could blow up an LLM's token budget
  3. NULL profile  - missing data distribution in key columns
  4. Type quirks   - data type inconsistencies vs schema declaration
  5. Integrity     - orphan records, broken foreign-key relationships
  6. Business      - rule violations, range checks, time-logic anomalies

Usage:
    python scripts/audit_data.py              # print to terminal
    python scripts/audit_data.py --markdown   # also write AUDIT_REPORT.md

Exit code:
    0 - audit ran successfully (regardless of findings)
    1 - database not found or unreadable
"""

import argparse
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "northwind.db"
REPORT_PATH = Path(__file__).resolve().parent.parent / "AUDIT_REPORT.md"


# ---------- Output helpers ----------
# We write to both a list (for the markdown report) and stdout (for terminal).

@dataclass
class AuditReport:
    """Collects findings from all audit passes."""
    lines: list[str] = field(default_factory=list)
    findings: list[dict[str, Any]] = field(default_factory=list)

    def section(self, title: str) -> None:
        self.lines.append("")
        self.lines.append(f"## {title}")
        self.lines.append("")

    def subsection(self, title: str) -> None:
        self.lines.append("")
        self.lines.append(f"### {title}")
        self.lines.append("")

    def text(self, line: str = "") -> None:
        self.lines.append(line)

    def table_header(self, headers: list[str]) -> None:
        self.lines.append("| " + " | ".join(headers) + " |")
        self.lines.append("|" + "|".join("---" for _ in headers) + "|")

    def table_row(self, cells: list[str]) -> None:
        self.lines.append("| " + " | ".join(cells) + " |")

    def finding(self, severity: str, category: str, message: str,
                resolution: str | None = None) -> None:
        """Record a discoverd issue. Severity: HIGH | MEDIUM | INFO | OK."""
        self.findings.append({
            "severity": severity,
            "category": category,
            "message": message,
            "resolution": resolution,
        })

    def print_to_terminal(self) -> None:
        """Render the report to stdout with simple ANSI color hints."""
        for line in self.lines:
            # Light styling for terminal — markdown headers become bold
            if line.startswith("# "):
                print(f"\n\033[1m{line[2:]}\033[0m")
            elif line.startswith("## "):
                print(f"\n\033[1;36m{line[3:]}\033[0m")
                print("-" * 70)
            elif line.startswith("### "):
                print(f"\n\033[1m{line[4:]}\033[0m")
            else:
                print(line)

    def write_markdown(self, path: Path) -> None:
        # Build a findings summary at the top of the markdown
        summary_lines = []
        sev_order = ["HIGH", "MEDIUM", "INFO", "OK"]
        by_sev = {s: [f for f in self.findings if f["severity"] == s] for s in sev_order}

        summary_lines.append("# Northwind Data Audit Report")
        summary_lines.append("")
        summary_lines.append(
            f"_Generated by `scripts/audit_data.py`. "
            f"This report is regenerated on every run — no manual editing._"
        )
        summary_lines.append("")
        summary_lines.append("## Executive Summary")
        summary_lines.append("")
        summary_lines.append("| Severity | Count |")
        summary_lines.append("|---|---|")
        for s in sev_order:
            summary_lines.append(f"| {s} | {len(by_sev[s])} |")

        full = summary_lines + self.lines
        path.write_text("\n".join(full), encoding="utf-8")


# ---------- Audit passes ----------

def audit_structure(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("1. Structural Audit")
    report.text("Table sizes and emptiness check.")
    report.text("")

    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    )
    tables = [r[0] for r in cur.fetchall()]

    report.table_header(["Table", "Row count", "Status"])
    for t in tables:
        n = cur.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        if n == 0:
            status = "⚠️ **EMPTY** — hidden from agent"
            report.finding(
                "MEDIUM", "Empty table", f"{t} has 0 rows",
                resolution=f"Hidden from agent's schema view via HIDDEN_TABLES",
            )
        else:
            status = "✅ OK"
        report.table_row([t, f"{n:,}", status])


def audit_blobs(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("2. BLOB Column Audit")
    report.text(
        "Binary columns can return tens of kilobytes per row. If the agent "
        "writes `SELECT *`, the result would explode the LLM's context window. "
        "We detect these by sampling the first row of every column."
    )
    report.text("")

    cur.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%'"
    )
    tables = [r[0] for r in cur.fetchall()]

    blob_findings = []
    for t in tables:
        cols = cur.execute(f'PRAGMA table_info("{t}")').fetchall()
        for c in cols:
            col_name = c[1]
            try:
                row = cur.execute(
                    f'SELECT "{col_name}" FROM "{t}" '
                    f'WHERE "{col_name}" IS NOT NULL LIMIT 1'
                ).fetchone()
                if row and isinstance(row[0], bytes):
                    blob_findings.append((t, col_name, len(row[0])))
            except Exception:
                pass  # column might not be queryable in some edge cases

    if blob_findings:
        report.table_header(["Table", "Column", "Bytes / row", "Resolution"])
        for t, c, size in blob_findings:
            report.table_row([
                t, c, f"{size:,}",
                "Hidden from schema + stripped from results",
            ])
            report.finding(
                "HIGH", "BLOB risk",
                f"{t}.{c} stores ~{size:,} bytes per row",
                resolution="Hidden from agent's schema + auto-stripped from any "
                           "SELECT * result. Defense in depth.",
            )
    else:
        report.text("✅ No BLOB columns detected.")
        report.finding("OK", "BLOB risk", "No BLOB columns found.")


def audit_nulls(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("3. NULL Distribution Audit")
    report.text(
        "Checks NULL frequency in business-critical columns. "
        "Not every NULL is an error — some encode real business meaning "
        "(e.g. `ShippedDate IS NULL` means 'not yet shipped')."
    )
    report.text("")

    checks = [
        ("Customers", "Region"),
        ("Orders", "ShippedDate"),
        ("Orders", "ShipRegion"),
        ("Orders", "CustomerID"),
        ("Orders", "EmployeeID"),
        ("Order Details", "Discount"),
        ("Suppliers", "Region"),
        ("Suppliers", "Fax"),
        ("Suppliers", "HomePage"),
        ("Products", "Discontinued"),
        ("Employees", "ReportsTo"),
    ]

    report.table_header(["Column", "NULL count", "% of total", "Interpretation"])
    for t, c in checks:
        total = cur.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
        nulls = cur.execute(
            f'SELECT COUNT(*) FROM "{t}" WHERE "{c}" IS NULL'
        ).fetchone()[0]
        pct = (nulls / total * 100) if total else 0

        if pct == 0:
            interp = "Complete"
            severity = "OK"
        elif pct < 5:
            interp = "Low — likely sparse data"
            severity = "INFO"
        elif pct < 30:
            interp = "Moderate — verify business meaning"
            severity = "INFO"
        else:
            interp = "High — may need NULL handling in queries"
            severity = "MEDIUM"

        report.table_row([
            f"`{t}.{c}`", f"{nulls:,}", f"{pct:.1f}%", interp
        ])

        if severity != "OK":
            report.finding(
                severity, "NULL distribution",
                f"{t}.{c} is {pct:.1f}% NULL ({nulls:,}/{total:,})",
                resolution="Kept as-is; NULLs often encode business meaning here.",
            )

    report.text("")
    report.text("**Decision:** No NULLs are deleted or imputed. They carry "
                "real business signal (e.g. unshipped orders, CEO without a "
                "manager, old suppliers without websites).")


def audit_types(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("4. Data Type Quirks")
    report.text(
        "Looking for columns whose actual values don't match the declared "
        "type, or where SQLite's flexible typing might mislead the agent."
    )
    report.text("")

    # Discontinued: declared TEXT, used as boolean
    distinct_disc = cur.execute(
        "SELECT DISTINCT Discontinued FROM Products"
    ).fetchall()
    report.subsection("Products.Discontinued")
    report.text(
        f"Declared type: TEXT. Distinct values: "
        f"{sorted([r[0] for r in distinct_disc])}"
    )
    report.text("")
    report.text(
        "**Quirk:** Stored as text `'0'` / `'1'`, not boolean. "
        "The agent must filter with `Discontinued = '1'` (string), "
        "not `Discontinued = 1` (integer)."
    )
    report.finding(
        "INFO", "Type quirk",
        "Products.Discontinued stored as TEXT '0'/'1', not BOOLEAN",
        resolution="System prompt explicitly tells the agent the correct syntax.",
    )

    # UnitPrice: integer in Products, float in Order Details
    report.subsection("UnitPrice across tables")
    prod_samples = cur.execute(
        "SELECT UnitPrice FROM Products LIMIT 5"
    ).fetchall()
    detail_samples = cur.execute(
        'SELECT UnitPrice FROM "Order Details" LIMIT 5'
    ).fetchall()
    report.text(f"`Products.UnitPrice` samples: {[r[0] for r in prod_samples]}")
    report.text(f"`Order Details.UnitPrice` samples: {[r[0] for r in detail_samples]}")
    report.text("")
    report.text(
        "**Quirk:** Products holds the *list price* (integer-ish), Order Details "
        "holds the *transaction price* (can be fractional due to historical "
        "pricing). These are intentionally different — not normalized."
    )

    # OrderDate timestamps
    report.subsection("Orders.OrderDate")
    date_samples = cur.execute(
        "SELECT DISTINCT OrderDate FROM Orders ORDER BY OrderDate LIMIT 3"
    ).fetchall()
    report.text(f"Format samples: {[r[0] for r in date_samples]}")
    report.text("")
    report.text(
        "Declared as DATETIME, stored as ISO 8601 strings. SQLite handles "
        "`strftime()` and `date()` correctly on these. No action needed."
    )

    # Discount range
    report.subsection("Order Details.Discount")
    disc = cur.execute(
        'SELECT MIN(Discount), MAX(Discount), AVG(Discount) FROM "Order Details"'
    ).fetchone()
    report.text(
        f"Range: {disc[0]} to {disc[1]}, average: {disc[2]:.4f}"
    )
    report.text("")
    report.text(
        "**Quirk:** Discount is a decimal (0.10 = 10%), not a percentage "
        "(10 ≠ 10%). The agent must multiply, not subtract."
    )
    report.finding(
        "INFO", "Type quirk",
        "Discount stored as decimal (0.0-0.25), not percentage",
        resolution="Revenue formula in system prompt: "
                   "Quantity * UnitPrice * (1 - Discount).",
    )


def audit_integrity(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("5. Referential Integrity Audit")
    report.text(
        "Foreign-key relationships should be unbroken: every order should "
        "have a valid customer, every line item should have a valid order."
    )
    report.text("")

    checks = [
        (
            "Orders → Customers",
            """SELECT COUNT(*) FROM Orders o
               LEFT JOIN Customers c ON o.CustomerID = c.CustomerID
               WHERE c.CustomerID IS NULL AND o.CustomerID IS NOT NULL""",
        ),
        (
            "Orders → Employees",
            """SELECT COUNT(*) FROM Orders o
               LEFT JOIN Employees e ON o.EmployeeID = e.EmployeeID
               WHERE e.EmployeeID IS NULL""",
        ),
        (
            "Order Details → Orders",
            """SELECT COUNT(*) FROM "Order Details" od
               LEFT JOIN Orders o ON od.OrderID = o.OrderID
               WHERE o.OrderID IS NULL""",
        ),
        (
            "Order Details → Products",
            """SELECT COUNT(*) FROM "Order Details" od
               LEFT JOIN Products p ON od.ProductID = p.ProductID
               WHERE p.ProductID IS NULL""",
        ),
        (
            "Products → Suppliers",
            """SELECT COUNT(*) FROM Products p
               LEFT JOIN Suppliers s ON p.SupplierID = s.SupplierID
               WHERE s.SupplierID IS NULL AND p.SupplierID IS NOT NULL""",
        ),
        (
            "Products → Categories",
            """SELECT COUNT(*) FROM Products p
               LEFT JOIN Categories c ON p.CategoryID = c.CategoryID
               WHERE c.CategoryID IS NULL AND p.CategoryID IS NOT NULL""",
        ),
    ]

    report.table_header(["Relationship", "Orphan count", "Status"])
    for label, sql in checks:
        n = cur.execute(sql).fetchone()[0]
        status = "✅ Clean" if n == 0 else f"⚠️ {n} orphans"
        report.table_row([label, f"{n:,}", status])
        if n > 0:
            report.finding(
                "HIGH", "Referential integrity",
                f"{label}: {n} orphan records",
                resolution="Manual investigation required before relying on these joins.",
            )
        else:
            report.finding("OK", "Referential integrity", f"{label}: clean")


def audit_business(cur: sqlite3.Cursor, report: AuditReport) -> None:
    report.section("6. Business Rule Audit")
    report.text("Sanity checks on numeric ranges and time logic.")
    report.text("")

    # Negative quantities
    bad_qty = cur.execute(
        'SELECT COUNT(*) FROM "Order Details" WHERE Quantity <= 0'
    ).fetchone()[0]
    report.text(f"- Line items with `Quantity <= 0`: **{bad_qty}**")

    # Shipped before ordered
    weird = cur.execute(
        """SELECT COUNT(*) FROM Orders
           WHERE ShippedDate IS NOT NULL AND ShippedDate < OrderDate"""
    ).fetchone()[0]
    report.text(f"- Orders shipped before order date: **{weird}**")

    # Discount > 1 (more than 100%)
    bad_disc = cur.execute(
        'SELECT COUNT(*) FROM "Order Details" WHERE Discount > 1 OR Discount < 0'
    ).fetchone()[0]
    report.text(f"- Line items with `Discount` outside [0, 1]: **{bad_disc}**")

    # Date range
    date_span = cur.execute(
        """SELECT MIN(OrderDate), MAX(OrderDate),
                  COUNT(DISTINCT strftime('%Y', OrderDate))
           FROM Orders"""
    ).fetchone()
    report.text(
        f"- Order date span: **{date_span[0][:10]}** to "
        f"**{date_span[1][:10]}** (~{date_span[2]} years)"
    )

    report.text("")
    if bad_qty == 0 and weird == 0 and bad_disc == 0:
        report.text("✅ All business-rule checks passed.")
        report.finding("OK", "Business rules", "All sanity checks passed.")
    else:
        report.finding(
            "HIGH", "Business rules",
            f"Quantity issues: {bad_qty}, time-logic issues: {weird}, "
            f"discount issues: {bad_disc}",
            resolution="Investigate before treating these rows as valid.",
        )

    # Time-window finding
    report.text("")
    report.text(
        f"**Decision:** The data ends in October 2023. "
        f"Rather than shift timestamps to make the data appear current "
        f"(which would be deceptive), the agent's system prompt tells it "
        f"explicitly: *'latest order date is 2023-10-28; interpret "
        f'\"this year\" / \"last month\" relative to this.\'*'
    )
    report.finding(
        "INFO", "Time window",
        f"Data ends {date_span[1][:10]} (not 'now')",
        resolution="Agent's system prompt anchors time-relative queries "
                   "to the actual data window. Honest > convenient.",
    )


# ---------- Findings summary ----------

def render_findings_summary(report: AuditReport) -> None:
    report.section("Findings Summary")

    sev_order = ["HIGH", "MEDIUM", "INFO", "OK"]
    sev_emoji = {"HIGH": "🚨", "MEDIUM": "⚠️", "INFO": "ℹ️", "OK": "✅"}

    by_sev: dict[str, list[dict[str, Any]]] = {s: [] for s in sev_order}
    for f in report.findings:
        by_sev[f["severity"]].append(f)

    counts = " · ".join(
        f"{sev_emoji[s]} {s}: {len(by_sev[s])}" for s in sev_order
    )
    report.text(f"**Counts:** {counts}")
    report.text("")

    for sev in sev_order:
        items = by_sev[sev]
        if not items:
            continue
        report.subsection(f"{sev_emoji[sev]} {sev} ({len(items)})")
        report.table_header(["Category", "Issue", "Resolution"])
        for f in items:
            report.table_row([
                f["category"],
                f["message"],
                f["resolution"] or "—",
            ])


# ---------- Main ----------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Audit the Northwind database for data quality issues."
    )
    parser.add_argument(
        "--markdown", action="store_true",
        help=f"Also write a markdown report to {REPORT_PATH.name}",
    )
    parser.add_argument(
        "--quiet", action="store_true",
        help="Suppress terminal output (useful with --markdown)",
    )
    args = parser.parse_args()

    if not DB_PATH.exists():
        print(f"❌ Database not found at {DB_PATH}")
        print("   Run: python scripts/init_db.py")
        return 1

    report = AuditReport()
    # Note: the markdown writer adds its own top-level title, so we use H2 here
    # for the database info banner. Terminal output strips markdown anyway.
    report.lines.append(
        f"_Database: `{DB_PATH.name}` "
        f"({DB_PATH.stat().st_size / 1024 / 1024:.1f} MB)_"
    )

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    try:
        audit_structure(cur, report)
        audit_blobs(cur, report)
        audit_nulls(cur, report)
        audit_types(cur, report)
        audit_integrity(cur, report)
        audit_business(cur, report)
        render_findings_summary(report)
    finally:
        conn.close()

    if not args.quiet:
        report.print_to_terminal()

    if args.markdown:
        report.write_markdown(REPORT_PATH)
        print(f"\n📄 Markdown report written to: {REPORT_PATH}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
